-- ExpeditionMaps.lua (ModuleScript, shared)
-- Definitions for the expedition maps. Each is a PROCEDURAL maze generated by
-- ExpeditionBuilder from `Width` x `Height` cells, so the layout is different
-- every server start and needs no bespoke art. The three maps are RISK/REWARD
-- TIERS: as you go down the list they get bigger, darker, and more crowded with
-- monsters — but the loot gets rarer (higher Luck).
--   Width/Height : maze size in 16-stud cells (bigger = easier to get lost)
--   Monsters     : number of roaming patrol monsters
--   Pickups      : how many artifacts exist at once
--   Fog          : how far you can see (smaller = darker / scarier)
--   Luck         : rarity bias — best-of-N artifact rolls (1 = normal)
-- The client reads Name/Description for the map chooser.

return {
	{
		Id = "tangle",
		Name = "The Tangle",
		Description = "The shallowest maze — your flashlight reaches a little further here and artifacts are plentiful. A good place to learn the dark.",
		Width = 10,
		Height = 9,
		Monsters = 3,
		Pickups = 8,
		Fog = 95,
		Luck = 1,
	},
	{
		Id = "warren",
		Name = "The Warren",
		Description = "Deeper, darker, and crawling with more of them. Fewer artifacts, but rarer finds for those who dare to wander.",
		Width = 13,
		Height = 12,
		Monsters = 5,
		Pickups = 7,
		Fog = 65,
		Luck = 2,
	},
	{
		Id = "sprawl",
		Name = "The Sprawl",
		Description = "Endless black corridors, packed with horrors and almost no light. But it hoards the rarest cursed relics — if you can find them and get out.",
		Width = 16,
		Height = 15,
		Monsters = 8,
		Pickups = 6,
		Fog = 45,
		Luck = 3,
	},
}
